sudo: required
services:
  - docker

before_install:
  - cd /project

install:
  - docker-compose -f docker-compose-dev up -d


script:
  - docker-compose -f docker-compose-dev exec
  - docker-compose -f docker-compose-dev.yml exec table_of_elements_test find -name "*.pyc" -delete
  - docker-compose -f docker-compose-dev.yml exec table_of_elements_test pytest /app/tests -v


