sudo: required
addons:
  ssh_known_hosts: 74.207.236.236
branches:
  only:
  - master
services:
- docker
before_install:
  - openssl aes-256-cbc -K $encrypted_ffdb65824e38_key -iv $encrypted_ffdb65824e38_iv -in travis_rsa.enc -out travis_rsa -d
  - chmod 600 travis_rsa
  - mv travis_rsa ~/.ssh/id_rsa
install:
  - docker-compose -f docker-compose-dev.yml up -d
script:
  - find -name "__pycache__" -prune -exec rm -rf '{}' \;
  - find -name ".pytest*" -prune -exec rm -rf '{}' \;
  - docker-compose -f docker-compose-dev.yml exec table_of_elements_test find -name "__pycache__" -prune -exec rm -rf '{}' \;
  - docker-compose -f docker-compose-dev.yml exec table_of_elements_test pytest /app/tests -v
after_script:
  - find -name "__pycache__" -prune -exec rm -rf '{}' \;
  - find -name ".pytest*" -prune -exec rm -rf '{}' \;
after_success:
  - bash ./deploy.sh
