sudo: required
branches:
  only:
  - master
services:
  - docker
install:
  - docker-compose -f docker-compose.yml up -d
script:
  - docker-compose -f docker-compose.yml exec table_of_elements find -name "__pyc*" -exec rm -rf '{}' \;
  - docker-compose -f docker-compose.yml exec table_of_elements pytest /app/tests -v
after_success:
  - bash ./deploy.sh
