version: "3"

services:
    table_of_elements:
        build:
            context: ./project
        volumes:
            - "./project/main/:/app"

        labels:
          - "traefik.backend=table_of_elements"
          - "traefik.frontend.rule=Host: halcyonramirez.com"
          - "traefik.docker.network=web"
          - "traefik.port=7777"
          - "traefik.enable=true"

        depends_on:
            - traefik


        networks:
            - web

    traefik:
        image: traefik
        restart: always
        ports:
          - 80:80
          - 443:443
          - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik/traefik.toml:/traefik.toml
          - ./traefik/acme.json:/acme.json
        networks:
          - web

networks:
    web:
        external: true




networks:
  web:
    external: true
